# fly.toml app configuration file generated for day05-2a202601925-ngohuyhoan-batch03-k4-ai-product-hackathon

app = "day05-2a202601925-ngohuyhoan-batch03-k4-ai-product-hackathon"
primary_region = "sin"
swap_size_mb = 512

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 8080
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
